// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_contacts_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contacts_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contacts_2eproto;
namespace contacts {
class Address;
struct AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Contacts;
struct ContactsDefaultTypeInternal;
extern ContactsDefaultTypeInternal _Contacts_default_instance_;
class PeopleInfo;
struct PeopleInfoDefaultTypeInternal;
extern PeopleInfoDefaultTypeInternal _PeopleInfo_default_instance_;
class PeopleInfo_RemarkEntry_DoNotUse;
struct PeopleInfo_RemarkEntry_DoNotUseDefaultTypeInternal;
extern PeopleInfo_RemarkEntry_DoNotUseDefaultTypeInternal _PeopleInfo_RemarkEntry_DoNotUse_default_instance_;
class Phone;
struct PhoneDefaultTypeInternal;
extern PhoneDefaultTypeInternal _Phone_default_instance_;
}  // namespace contacts
PROTOBUF_NAMESPACE_OPEN
template<> ::contacts::Address* Arena::CreateMaybeMessage<::contacts::Address>(Arena*);
template<> ::contacts::Contacts* Arena::CreateMaybeMessage<::contacts::Contacts>(Arena*);
template<> ::contacts::PeopleInfo* Arena::CreateMaybeMessage<::contacts::PeopleInfo>(Arena*);
template<> ::contacts::PeopleInfo_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage<::contacts::PeopleInfo_RemarkEntry_DoNotUse>(Arena*);
template<> ::contacts::Phone* Arena::CreateMaybeMessage<::contacts::Phone>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace contacts {

enum Phone_PhoneType : int {
  Phone_PhoneType_MP = 0,
  Phone_PhoneType_TEL = 1,
  Phone_PhoneType_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Phone_PhoneType_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Phone_PhoneType_IsValid(int value);
constexpr Phone_PhoneType Phone_PhoneType_PhoneType_MIN = Phone_PhoneType_MP;
constexpr Phone_PhoneType Phone_PhoneType_PhoneType_MAX = Phone_PhoneType_TEL;
constexpr int Phone_PhoneType_PhoneType_ARRAYSIZE = Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool Phone_PhoneType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Phone_PhoneType>(
    Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class Phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Phone) */ {
 public:
  inline Phone() : Phone(nullptr) {}
  ~Phone() override;
  explicit PROTOBUF_CONSTEXPR Phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Phone(const Phone& from);
  Phone(Phone&& from) noexcept
    : Phone() {
    *this = ::std::move(from);
  }

  inline Phone& operator=(const Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline Phone& operator=(Phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const Phone* internal_default_instance() {
    return reinterpret_cast<const Phone*>(
               &_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Phone& a, Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(Phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Phone& from) {
    Phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Phone";
  }
  protected:
  explicit Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Phone_PhoneType PhoneType;
  static constexpr PhoneType MP =
    Phone_PhoneType_MP;
  static constexpr PhoneType TEL =
    Phone_PhoneType_TEL;
  static inline bool PhoneType_IsValid(int value) {
    return Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PhoneType* value) {
    return Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string phone_number = 1;
  void clear_phone_number();
  const std::string& phone_number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_phone_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_phone_number();
  PROTOBUF_NODISCARD std::string* release_phone_number();
  void set_allocated_phone_number(std::string* phone_number);
  private:
  const std::string& _internal_phone_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_phone_number(const std::string& value);
  std::string* _internal_mutable_phone_number();
  public:

  // .contacts.Phone.PhoneType type = 2;
  void clear_type();
  ::contacts::Phone_PhoneType type() const;
  void set_type(::contacts::Phone_PhoneType value);
  private:
  ::contacts::Phone_PhoneType _internal_type() const;
  void _internal_set_type(::contacts::Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:contacts.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phone_number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class Address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Address) */ {
 public:
  inline Address() : Address(nullptr) {}
  ~Address() override;
  explicit PROTOBUF_CONSTEXPR Address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Address* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Address& from) {
    Address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Address";
  }
  protected:
  explicit Address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHomeAddrFieldNumber = 1,
    kUnitAddrFieldNumber = 2,
  };
  // string home_addr = 1;
  void clear_home_addr();
  const std::string& home_addr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_home_addr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_home_addr();
  PROTOBUF_NODISCARD std::string* release_home_addr();
  void set_allocated_home_addr(std::string* home_addr);
  private:
  const std::string& _internal_home_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_home_addr(const std::string& value);
  std::string* _internal_mutable_home_addr();
  public:

  // string unit_addr = 2;
  void clear_unit_addr();
  const std::string& unit_addr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_unit_addr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_unit_addr();
  PROTOBUF_NODISCARD std::string* release_unit_addr();
  void set_allocated_unit_addr(std::string* unit_addr);
  private:
  const std::string& _internal_unit_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_unit_addr(const std::string& value);
  std::string* _internal_mutable_unit_addr();
  public:

  // @@protoc_insertion_point(class_scope:contacts.Address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr home_addr_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr unit_addr_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class PeopleInfo_RemarkEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PeopleInfo_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PeopleInfo_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  PeopleInfo_RemarkEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PeopleInfo_RemarkEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PeopleInfo_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PeopleInfo_RemarkEntry_DoNotUse& other);
  static const PeopleInfo_RemarkEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PeopleInfo_RemarkEntry_DoNotUse*>(&_PeopleInfo_RemarkEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "contacts.PeopleInfo.RemarkEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "contacts.PeopleInfo.RemarkEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_contacts_2eproto;
};

// -------------------------------------------------------------------

class PeopleInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.PeopleInfo) */ {
 public:
  inline PeopleInfo() : PeopleInfo(nullptr) {}
  ~PeopleInfo() override;
  explicit PROTOBUF_CONSTEXPR PeopleInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeopleInfo(const PeopleInfo& from);
  PeopleInfo(PeopleInfo&& from) noexcept
    : PeopleInfo() {
    *this = ::std::move(from);
  }

  inline PeopleInfo& operator=(const PeopleInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeopleInfo& operator=(PeopleInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeopleInfo& default_instance() {
    return *internal_default_instance();
  }
  enum OtherContactCase {
    kQq = 5,
    kWechat = 6,
    OTHER_CONTACT_NOT_SET = 0,
  };

  static inline const PeopleInfo* internal_default_instance() {
    return reinterpret_cast<const PeopleInfo*>(
               &_PeopleInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PeopleInfo& a, PeopleInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PeopleInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeopleInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeopleInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeopleInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeopleInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeopleInfo& from) {
    PeopleInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeopleInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.PeopleInfo";
  }
  protected:
  explicit PeopleInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kPhoneFieldNumber = 3,
    kRemarkFieldNumber = 7,
    kNameFieldNumber = 1,
    kAddrFieldNumber = 4,
    kAgeFieldNumber = 2,
    kQqFieldNumber = 5,
    kWechatFieldNumber = 6,
  };
  // repeated .contacts.Phone phone = 3;
  int phone_size() const;
  private:
  int _internal_phone_size() const;
  public:
  void clear_phone();
  ::contacts::Phone* mutable_phone(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >*
      mutable_phone();
  private:
  const ::contacts::Phone& _internal_phone(int index) const;
  ::contacts::Phone* _internal_add_phone();
  public:
  const ::contacts::Phone& phone(int index) const;
  ::contacts::Phone* add_phone();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >&
      phone() const;

  // map<string, string> remark = 7;
  int remark_size() const;
  private:
  int _internal_remark_size() const;
  public:
  void clear_remark();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_remark();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_remark();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .google.protobuf.Any addr = 4;
  bool has_addr() const;
  private:
  bool _internal_has_addr() const;
  public:
  void clear_addr();
  const ::PROTOBUF_NAMESPACE_ID::Any& addr() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_addr();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_addr();
  void set_allocated_addr(::PROTOBUF_NAMESPACE_ID::Any* addr);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_addr() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_addr();
  public:
  void unsafe_arena_set_allocated_addr(
      ::PROTOBUF_NAMESPACE_ID::Any* addr);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_addr();

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // string qq = 5;
  bool has_qq() const;
  private:
  bool _internal_has_qq() const;
  public:
  void clear_qq();
  const std::string& qq() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qq(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qq();
  PROTOBUF_NODISCARD std::string* release_qq();
  void set_allocated_qq(std::string* qq);
  private:
  const std::string& _internal_qq() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qq(const std::string& value);
  std::string* _internal_mutable_qq();
  public:

  // string wechat = 6;
  bool has_wechat() const;
  private:
  bool _internal_has_wechat() const;
  public:
  void clear_wechat();
  const std::string& wechat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wechat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wechat();
  PROTOBUF_NODISCARD std::string* release_wechat();
  void set_allocated_wechat(std::string* wechat);
  private:
  const std::string& _internal_wechat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wechat(const std::string& value);
  std::string* _internal_mutable_wechat();
  public:

  void clear_other_contact();
  OtherContactCase other_contact_case() const;
  // @@protoc_insertion_point(class_scope:contacts.PeopleInfo)
 private:
  class _Internal;
  void set_has_qq();
  void set_has_wechat();

  inline bool has_other_contact() const;
  inline void clear_has_other_contact();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone > phone_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PeopleInfo_RemarkEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> remark_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::Any* addr_;
    int32_t age_;
    union OtherContactUnion {
      constexpr OtherContactUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qq_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wechat_;
    } other_contact_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class Contacts final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Contacts) */ {
 public:
  inline Contacts() : Contacts(nullptr) {}
  ~Contacts() override;
  explicit PROTOBUF_CONSTEXPR Contacts(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Contacts(const Contacts& from);
  Contacts(Contacts&& from) noexcept
    : Contacts() {
    *this = ::std::move(from);
  }

  inline Contacts& operator=(const Contacts& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contacts& operator=(Contacts&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Contacts& default_instance() {
    return *internal_default_instance();
  }
  static inline const Contacts* internal_default_instance() {
    return reinterpret_cast<const Contacts*>(
               &_Contacts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Contacts& a, Contacts& b) {
    a.Swap(&b);
  }
  inline void Swap(Contacts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Contacts* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Contacts* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Contacts>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Contacts& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Contacts& from) {
    Contacts::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contacts* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Contacts";
  }
  protected:
  explicit Contacts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContactsFieldNumber = 1,
  };
  // repeated .contacts.PeopleInfo contacts = 1;
  int contacts_size() const;
  private:
  int _internal_contacts_size() const;
  public:
  void clear_contacts();
  ::contacts::PeopleInfo* mutable_contacts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::PeopleInfo >*
      mutable_contacts();
  private:
  const ::contacts::PeopleInfo& _internal_contacts(int index) const;
  ::contacts::PeopleInfo* _internal_add_contacts();
  public:
  const ::contacts::PeopleInfo& contacts(int index) const;
  ::contacts::PeopleInfo* add_contacts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::PeopleInfo >&
      contacts() const;

  // @@protoc_insertion_point(class_scope:contacts.Contacts)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::PeopleInfo > contacts_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Phone

// string phone_number = 1;
inline void Phone::clear_phone_number() {
  _impl_.phone_number_.ClearToEmpty();
}
inline const std::string& Phone::phone_number() const {
  // @@protoc_insertion_point(field_get:contacts.Phone.phone_number)
  return _internal_phone_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Phone::set_phone_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.phone_number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Phone.phone_number)
}
inline std::string* Phone::mutable_phone_number() {
  std::string* _s = _internal_mutable_phone_number();
  // @@protoc_insertion_point(field_mutable:contacts.Phone.phone_number)
  return _s;
}
inline const std::string& Phone::_internal_phone_number() const {
  return _impl_.phone_number_.Get();
}
inline void Phone::_internal_set_phone_number(const std::string& value) {
  
  _impl_.phone_number_.Set(value, GetArenaForAllocation());
}
inline std::string* Phone::_internal_mutable_phone_number() {
  
  return _impl_.phone_number_.Mutable(GetArenaForAllocation());
}
inline std::string* Phone::release_phone_number() {
  // @@protoc_insertion_point(field_release:contacts.Phone.phone_number)
  return _impl_.phone_number_.Release();
}
inline void Phone::set_allocated_phone_number(std::string* phone_number) {
  if (phone_number != nullptr) {
    
  } else {
    
  }
  _impl_.phone_number_.SetAllocated(phone_number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.phone_number_.IsDefault()) {
    _impl_.phone_number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Phone.phone_number)
}

// .contacts.Phone.PhoneType type = 2;
inline void Phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::contacts::Phone_PhoneType Phone::_internal_type() const {
  return static_cast< ::contacts::Phone_PhoneType >(_impl_.type_);
}
inline ::contacts::Phone_PhoneType Phone::type() const {
  // @@protoc_insertion_point(field_get:contacts.Phone.type)
  return _internal_type();
}
inline void Phone::_internal_set_type(::contacts::Phone_PhoneType value) {
  
  _impl_.type_ = value;
}
inline void Phone::set_type(::contacts::Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:contacts.Phone.type)
}

// -------------------------------------------------------------------

// Address

// string home_addr = 1;
inline void Address::clear_home_addr() {
  _impl_.home_addr_.ClearToEmpty();
}
inline const std::string& Address::home_addr() const {
  // @@protoc_insertion_point(field_get:contacts.Address.home_addr)
  return _internal_home_addr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_home_addr(ArgT0&& arg0, ArgT... args) {
 
 _impl_.home_addr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Address.home_addr)
}
inline std::string* Address::mutable_home_addr() {
  std::string* _s = _internal_mutable_home_addr();
  // @@protoc_insertion_point(field_mutable:contacts.Address.home_addr)
  return _s;
}
inline const std::string& Address::_internal_home_addr() const {
  return _impl_.home_addr_.Get();
}
inline void Address::_internal_set_home_addr(const std::string& value) {
  
  _impl_.home_addr_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_home_addr() {
  
  return _impl_.home_addr_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_home_addr() {
  // @@protoc_insertion_point(field_release:contacts.Address.home_addr)
  return _impl_.home_addr_.Release();
}
inline void Address::set_allocated_home_addr(std::string* home_addr) {
  if (home_addr != nullptr) {
    
  } else {
    
  }
  _impl_.home_addr_.SetAllocated(home_addr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.home_addr_.IsDefault()) {
    _impl_.home_addr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Address.home_addr)
}

// string unit_addr = 2;
inline void Address::clear_unit_addr() {
  _impl_.unit_addr_.ClearToEmpty();
}
inline const std::string& Address::unit_addr() const {
  // @@protoc_insertion_point(field_get:contacts.Address.unit_addr)
  return _internal_unit_addr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_unit_addr(ArgT0&& arg0, ArgT... args) {
 
 _impl_.unit_addr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Address.unit_addr)
}
inline std::string* Address::mutable_unit_addr() {
  std::string* _s = _internal_mutable_unit_addr();
  // @@protoc_insertion_point(field_mutable:contacts.Address.unit_addr)
  return _s;
}
inline const std::string& Address::_internal_unit_addr() const {
  return _impl_.unit_addr_.Get();
}
inline void Address::_internal_set_unit_addr(const std::string& value) {
  
  _impl_.unit_addr_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_unit_addr() {
  
  return _impl_.unit_addr_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_unit_addr() {
  // @@protoc_insertion_point(field_release:contacts.Address.unit_addr)
  return _impl_.unit_addr_.Release();
}
inline void Address::set_allocated_unit_addr(std::string* unit_addr) {
  if (unit_addr != nullptr) {
    
  } else {
    
  }
  _impl_.unit_addr_.SetAllocated(unit_addr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.unit_addr_.IsDefault()) {
    _impl_.unit_addr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Address.unit_addr)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PeopleInfo

// string name = 1;
inline void PeopleInfo::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PeopleInfo::name() const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeopleInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.PeopleInfo.name)
}
inline std::string* PeopleInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:contacts.PeopleInfo.name)
  return _s;
}
inline const std::string& PeopleInfo::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PeopleInfo::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_name() {
  // @@protoc_insertion_point(field_release:contacts.PeopleInfo.name)
  return _impl_.name_.Release();
}
inline void PeopleInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.PeopleInfo.name)
}

// int32 age = 2;
inline void PeopleInfo::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t PeopleInfo::_internal_age() const {
  return _impl_.age_;
}
inline int32_t PeopleInfo::age() const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.age)
  return _internal_age();
}
inline void PeopleInfo::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void PeopleInfo::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:contacts.PeopleInfo.age)
}

// repeated .contacts.Phone phone = 3;
inline int PeopleInfo::_internal_phone_size() const {
  return _impl_.phone_.size();
}
inline int PeopleInfo::phone_size() const {
  return _internal_phone_size();
}
inline void PeopleInfo::clear_phone() {
  _impl_.phone_.Clear();
}
inline ::contacts::Phone* PeopleInfo::mutable_phone(int index) {
  // @@protoc_insertion_point(field_mutable:contacts.PeopleInfo.phone)
  return _impl_.phone_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >*
PeopleInfo::mutable_phone() {
  // @@protoc_insertion_point(field_mutable_list:contacts.PeopleInfo.phone)
  return &_impl_.phone_;
}
inline const ::contacts::Phone& PeopleInfo::_internal_phone(int index) const {
  return _impl_.phone_.Get(index);
}
inline const ::contacts::Phone& PeopleInfo::phone(int index) const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.phone)
  return _internal_phone(index);
}
inline ::contacts::Phone* PeopleInfo::_internal_add_phone() {
  return _impl_.phone_.Add();
}
inline ::contacts::Phone* PeopleInfo::add_phone() {
  ::contacts::Phone* _add = _internal_add_phone();
  // @@protoc_insertion_point(field_add:contacts.PeopleInfo.phone)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >&
PeopleInfo::phone() const {
  // @@protoc_insertion_point(field_list:contacts.PeopleInfo.phone)
  return _impl_.phone_;
}

// .google.protobuf.Any addr = 4;
inline bool PeopleInfo::_internal_has_addr() const {
  return this != internal_default_instance() && _impl_.addr_ != nullptr;
}
inline bool PeopleInfo::has_addr() const {
  return _internal_has_addr();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& PeopleInfo::_internal_addr() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = _impl_.addr_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& PeopleInfo::addr() const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.addr)
  return _internal_addr();
}
inline void PeopleInfo::unsafe_arena_set_allocated_addr(
    ::PROTOBUF_NAMESPACE_ID::Any* addr) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.addr_);
  }
  _impl_.addr_ = addr;
  if (addr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contacts.PeopleInfo.addr)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::release_addr() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.addr_;
  _impl_.addr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::unsafe_arena_release_addr() {
  // @@protoc_insertion_point(field_release:contacts.PeopleInfo.addr)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.addr_;
  _impl_.addr_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::_internal_mutable_addr() {
  
  if (_impl_.addr_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    _impl_.addr_ = p;
  }
  return _impl_.addr_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::mutable_addr() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_addr();
  // @@protoc_insertion_point(field_mutable:contacts.PeopleInfo.addr)
  return _msg;
}
inline void PeopleInfo::set_allocated_addr(::PROTOBUF_NAMESPACE_ID::Any* addr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.addr_);
  }
  if (addr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(addr));
    if (message_arena != submessage_arena) {
      addr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, addr, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.addr_ = addr;
  // @@protoc_insertion_point(field_set_allocated:contacts.PeopleInfo.addr)
}

// string qq = 5;
inline bool PeopleInfo::_internal_has_qq() const {
  return other_contact_case() == kQq;
}
inline bool PeopleInfo::has_qq() const {
  return _internal_has_qq();
}
inline void PeopleInfo::set_has_qq() {
  _impl_._oneof_case_[0] = kQq;
}
inline void PeopleInfo::clear_qq() {
  if (_internal_has_qq()) {
    _impl_.other_contact_.qq_.Destroy();
    clear_has_other_contact();
  }
}
inline const std::string& PeopleInfo::qq() const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.qq)
  return _internal_qq();
}
template <typename ArgT0, typename... ArgT>
inline void PeopleInfo::set_qq(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  _impl_.other_contact_.qq_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.PeopleInfo.qq)
}
inline std::string* PeopleInfo::mutable_qq() {
  std::string* _s = _internal_mutable_qq();
  // @@protoc_insertion_point(field_mutable:contacts.PeopleInfo.qq)
  return _s;
}
inline const std::string& PeopleInfo::_internal_qq() const {
  if (_internal_has_qq()) {
    return _impl_.other_contact_.qq_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PeopleInfo::_internal_set_qq(const std::string& value) {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  _impl_.other_contact_.qq_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_qq() {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  return _impl_.other_contact_.qq_.Mutable(      GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_qq() {
  // @@protoc_insertion_point(field_release:contacts.PeopleInfo.qq)
  if (_internal_has_qq()) {
    clear_has_other_contact();
    return _impl_.other_contact_.qq_.Release();
  } else {
    return nullptr;
  }
}
inline void PeopleInfo::set_allocated_qq(std::string* qq) {
  if (has_other_contact()) {
    clear_other_contact();
  }
  if (qq != nullptr) {
    set_has_qq();
    _impl_.other_contact_.qq_.InitAllocated(qq, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.PeopleInfo.qq)
}

// string wechat = 6;
inline bool PeopleInfo::_internal_has_wechat() const {
  return other_contact_case() == kWechat;
}
inline bool PeopleInfo::has_wechat() const {
  return _internal_has_wechat();
}
inline void PeopleInfo::set_has_wechat() {
  _impl_._oneof_case_[0] = kWechat;
}
inline void PeopleInfo::clear_wechat() {
  if (_internal_has_wechat()) {
    _impl_.other_contact_.wechat_.Destroy();
    clear_has_other_contact();
  }
}
inline const std::string& PeopleInfo::wechat() const {
  // @@protoc_insertion_point(field_get:contacts.PeopleInfo.wechat)
  return _internal_wechat();
}
template <typename ArgT0, typename... ArgT>
inline void PeopleInfo::set_wechat(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  _impl_.other_contact_.wechat_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.PeopleInfo.wechat)
}
inline std::string* PeopleInfo::mutable_wechat() {
  std::string* _s = _internal_mutable_wechat();
  // @@protoc_insertion_point(field_mutable:contacts.PeopleInfo.wechat)
  return _s;
}
inline const std::string& PeopleInfo::_internal_wechat() const {
  if (_internal_has_wechat()) {
    return _impl_.other_contact_.wechat_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PeopleInfo::_internal_set_wechat(const std::string& value) {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  _impl_.other_contact_.wechat_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_wechat() {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  return _impl_.other_contact_.wechat_.Mutable(      GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_wechat() {
  // @@protoc_insertion_point(field_release:contacts.PeopleInfo.wechat)
  if (_internal_has_wechat()) {
    clear_has_other_contact();
    return _impl_.other_contact_.wechat_.Release();
  } else {
    return nullptr;
  }
}
inline void PeopleInfo::set_allocated_wechat(std::string* wechat) {
  if (has_other_contact()) {
    clear_other_contact();
  }
  if (wechat != nullptr) {
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitAllocated(wechat, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.PeopleInfo.wechat)
}

// map<string, string> remark = 7;
inline int PeopleInfo::_internal_remark_size() const {
  return _impl_.remark_.size();
}
inline int PeopleInfo::remark_size() const {
  return _internal_remark_size();
}
inline void PeopleInfo::clear_remark() {
  _impl_.remark_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PeopleInfo::_internal_remark() const {
  return _impl_.remark_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PeopleInfo::remark() const {
  // @@protoc_insertion_point(field_map:contacts.PeopleInfo.remark)
  return _internal_remark();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PeopleInfo::_internal_mutable_remark() {
  return _impl_.remark_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PeopleInfo::mutable_remark() {
  // @@protoc_insertion_point(field_mutable_map:contacts.PeopleInfo.remark)
  return _internal_mutable_remark();
}

inline bool PeopleInfo::has_other_contact() const {
  return other_contact_case() != OTHER_CONTACT_NOT_SET;
}
inline void PeopleInfo::clear_has_other_contact() {
  _impl_._oneof_case_[0] = OTHER_CONTACT_NOT_SET;
}
inline PeopleInfo::OtherContactCase PeopleInfo::other_contact_case() const {
  return PeopleInfo::OtherContactCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Contacts

// repeated .contacts.PeopleInfo contacts = 1;
inline int Contacts::_internal_contacts_size() const {
  return _impl_.contacts_.size();
}
inline int Contacts::contacts_size() const {
  return _internal_contacts_size();
}
inline void Contacts::clear_contacts() {
  _impl_.contacts_.Clear();
}
inline ::contacts::PeopleInfo* Contacts::mutable_contacts(int index) {
  // @@protoc_insertion_point(field_mutable:contacts.Contacts.contacts)
  return _impl_.contacts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::PeopleInfo >*
Contacts::mutable_contacts() {
  // @@protoc_insertion_point(field_mutable_list:contacts.Contacts.contacts)
  return &_impl_.contacts_;
}
inline const ::contacts::PeopleInfo& Contacts::_internal_contacts(int index) const {
  return _impl_.contacts_.Get(index);
}
inline const ::contacts::PeopleInfo& Contacts::contacts(int index) const {
  // @@protoc_insertion_point(field_get:contacts.Contacts.contacts)
  return _internal_contacts(index);
}
inline ::contacts::PeopleInfo* Contacts::_internal_add_contacts() {
  return _impl_.contacts_.Add();
}
inline ::contacts::PeopleInfo* Contacts::add_contacts() {
  ::contacts::PeopleInfo* _add = _internal_add_contacts();
  // @@protoc_insertion_point(field_add:contacts.Contacts.contacts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::PeopleInfo >&
Contacts::contacts() const {
  // @@protoc_insertion_point(field_list:contacts.Contacts.contacts)
  return _impl_.contacts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace contacts

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::contacts::Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::contacts::Phone_PhoneType>() {
  return ::contacts::Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto
